# Circle CI 2.0 Config File
# This config file will prevent tests from being run on the gh-pages branch.
version: 2
jobs:
  build:
    machine: true
    branches:
      ignore: gh-pages
      ignore: master
    steps:
      - run: echo "Skipping tests on gh-pages/master branch"